# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ba3031b641e25714ddc90ea837583bc1d4377bedd09255b1c71f8cd3a5b50b260a1f5b6f6fca319897259f077d2820fb98c2b11f5fa20322c25976883f4b2989

test:
  secret_key_base: ca6c4a734453bb7ea0017fad2e69e0dcdf6fc2c9a0758f92b6caf3a0be89a9612a5454704c9c4f6ae5b6174f8db03cd71b2fe6f816d94a805ad3264f0c87f11e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
